[package]
name = "openconnect-sso"
version = "0.9.0"
edition = "2024"
description = "Cisco AnyConnect SSO-v2 authentication for OpenConnect"
license = "GPL-3.0-only"
repository = "https://github.com/AleksanderEvensen/openconnect-sso"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["blocking", "cookies"] }
tao = "0.36.0"
wry = "0.56.1"
xmltree = "0.12.0"
